### ISSUE TITLE
I have a strange issue in your tool.

### ISSUE THREAD

**Issue by pinkopaio8** [Darkmet98/Monika#1]
Hi! I love your tool, it's very simple to use and it made my life easy. But there's a little problem:
When I try to import a .po file with your tool, it gives me back a strange exception:
![image](https://user-images.githubusercontent.com/29263287/70382889-10f2e800-1964-11ea-9c84-ce2fafee473f.png)
The .po file I'm trying to import it's been exported with your tool, and it worked fine. I've already imported another .po file and it worked fine too, but this one gives me this issue. I don't know what to do, since I don't know where to put my hands on. Any tips? Thank you.

Edit: I've already tried the "fix_import" fix, but it says that "this is not a Rpy file.", but it is.
![image](https://user-images.githubusercontent.com/29263287/70383078-ee62ce00-1967-11ea-8b58-4551e044badd.png)

**Comment by Darkmet98** [comment]
Ok! @pinkopaio8 Please send me your Po and Rpy files and give me a few hours to research the problem.

**Comment by Darkmet98** [comment]
fixed @pinkopaio8 download the new version ^^
https://github.com/Darkmet98/Monika/releases/download/1.2/Monika_Windows.exe
